#!/bin/bash

# © RDY SOFTWARE | 2016 - 2017 All rights reserved

clear

if [ $(id -u) -eq 0 ]
then
clear
else
	if echo $(id) |grep sudo > /dev/null
	then
	clear
	echo "Você não é root"
	echo "Seu usuário esta no grupo sudo"
	echo -e "Para tornar-se root execute \033[1;31msudo su\033[0m"
	exit
	else
	clear
	echo -e "Você não está como usuário root, nem com seus direitos (sudo)\nPara tornar-se root execute \033[1;31msu\033[0m e digite sua senha root"
	exit
	fi
fi


if [ -d /etc/tomada ]
then
echo ""
else
mkdir /etc/tomada
fi

if [ -d /etc/mtvps ]
then
echo ""
else
mkdir /etc/mtvps
fi

if [ -d /etc/tomada/senha ]
then
echo ""
else
mkdir /etc/tomada/senha
fi

if [ -d /etc/tomada/limite ]
then
echo ""
else
mkdir /etc/tomada/limite
fi

#RDY SOFTWARE

ip=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)

if [[ "$ip" = "" ]]; then
ip=$(wget -qO- ipv4.icanhazip.com)
fi

rdy_update(){
echo "working update!";
}

####

rdy_rsquid(){
echo -e "\033[1;31mRestarting SQUID service...\033[0m"
service squid restart 1> /dev/null 2> /dev/null
service squid3 restart 1> /dev/null 2> /dev/null
echo -e "\033[1;32m √ OK √ \033[0m"
}

####

rdy_rssh(){
echo -e "\033[1;31mRestarting SSH service...\033[0m"
service ssh restart 1> /dev/null 2> /dev/null
service sshd restart 1> /dev/null 2> /dev/null
echo -e "\033[1;32m √ OK √ \033[0m"
}

####

rdy_reboot(){
echo -e "\033[1;36mRebooting... Bye! \033[0m"
sleep 2
reboot
}

####

rdy_uninstall(){
echo "working uninstall!";
rm /bin/rdyLe
rm /bin/rdyau
rm /bin/rdydu
rm /bin/rdyMl
rm /bin/rdybk
rm /bin/limit
rm /bin/rdyMd
rm /bin/rdyrb
rm /bin/rdynew
rm /bin/rdy_menu

echo -e "\033[1;32m√ OK √ \033[0m"
}

####

help(){
echo "working update!";
}

####

echo "";

echo -e "\033[1;32m© RDY SOFTWARE | 2016 - 2017 All rights reserved\033[0m";
echo "";
echo "----------------------------------------------------";
echo -e "\033[1;32m -> \033[01;37mIP:\033[1;31m $ip";
echo "";
echo -e "\033[1;32m -> \033[01;37mOPERATIONAL SYSTEM:\033[1;31m $(cat /etc/so)";
echo "----------------------------------------------------";
echo -e "\033[1;36m[ # CTRL + C to exit # ]\033[0m"
echo "";
echo -e "\033[1;33m[01] Restart SSH Server \033[0m";
echo -e "\033[1;33m[02] Restart SQUID Proxy \033[0m";
echo -e "\033[1;33m[03] REBOOT SERVER \033[0m";
echo -e "\033[1;33m[04] Update script \033[0m";
echo -e "\033[1;33m[05] Uninstall script  \033[0m";
echo -e "\033[1;33m[06] Help \033[0m";
echo "";
echo -e "\033[1;32m[07] ADD USER \033[0m";
echo -e "\033[1;32m[08] DELETE USER \033[0m";
echo -e "\033[1;32m[09] Configure server (OpenSSH) \033[0m"
echo -e "\033[1;36m[01-09]: "; read -p ""  option

   case $option in
1 | 01) rdy_rssh ;;
2 | 02) rdy_rsquid ;;
3 | 03) rdy_reboot ;;
4 | 04) rdy_update ;;
5 | 05) rdy_uninstall ;;
6 | 06) rdy_help ;;
7 | 07) rdyau ;;
8 | 08) rdydu ;;
9 | 09) configserver.rdy ;;
 *) "Unknown option." ; echo ; sleep 2 ; rdy_menu ;;
   esac
