#!/bin/bash


cd
if [ $(id -u) -eq 0 ]
then
        clear
else
        if echo $(id) |grep sudo > /dev/null
        then
        clear
        echo "Você não é root"
        echo "Seu usuário está no grupo sudo"
        echo -e "Para virar root e fazer a instalação execute \033[1;31msudo su\033[0m"
        exit
        else
        clear
        echo -e "Você pecisa está como root para poder fazer a instalção. Para tornar-se root execute \033[1;31msu\033[0m e digite sua senha root"
        exit
        fi
fi


if
apt-get install -y git
git clone https://github.com/RDY8799/SSHNation.git
clear
cd SSHNation
rm -rf README.md
rm -rf rdyinstall
for arqs in `ls`
do
rm /bin/$arqs 2>/dev/null
mv $arqs /bin
chmod +x /bin/$arqs
done
echo -e "\033[1;32m√ Menu de configuração instalado com sucesso!\n\nDigite rdy_menu.\033[0m"
echo ""
cd

fi
rm -rf rdyinstal* 2> /dev/null
rm rdyinstal* 2> /dev/null
rm -rf SSHNatio* 2> /dev/null