#!/bin/bash

read -p "RDY" user
 if cat /etc/passwd |grep $user: > /dev/null
then
read -p "RDY" logins
  limit $user $logins
echo ""
echo "√ OK √ User: $user -> Limit: $logins";
 else
 clear
echo "User $user not found";
exit
 fi
exit
fi
