#!/bin/bash

#RDY SOFTWARE
# © RDY SOFTWARE | 2016 - 2017 All rights reserved

arq=$1
clear

for user in `cat $arq`
do
usuario=$(echo "$user" |awk -F : '{print $1}')
senha=$(echo "$user" |awk -F : '{print $2}')

if cat /etc/passwd |grep $usuario: 1> /dev/null 2>/dev/null
then
echo " " > /dev/null
else
echo "$user" |cut -d: -f3 1> /dev/null 2>/dev/null
  if [ $? = 0 ]
  then
  limite=$(echo "$user" |awk -F : '{print $3}')
   data=$(echo "$user" |awk -F : '{print $4}')
  useradd -M -s /bin/false $usuario
  (echo $senha ; echo $senha) | passwd $usuario > /dev/null 2> /dev/null
  limit $usuario $limite 1> /dev/null 2> /dev/null
  echo "$senha" > /etc/tomada/senha/$usuario
  chage -E $data $usuario 2> /dev/null
  chage -W 3 $usuario 2> /dev/null
echo "$usuario" > /etc/tomada/rdy_date/$usuario
  else
  useradd -M -s /bin/false $usuario
  (echo $senha ; echo $senha) | passwd $usuario > /dev/null 2> /dev/null
  echo "$senha" > /etc/tomada/senha/$usuario
  fi
echo "√ Finished! OK √";
fi
done
